import { createContext, useContext, useEffect, useState } from "react"

export type Language = "en" | "pidgin"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.features": "Features",
    "nav.how_it_works": "How It Works",
    "nav.pricing": "Pricing",
    "nav.about": "About",
    "nav.client_portal": "Client Portal",
    "nav.get_started": "Get Started",
    "nav.get_early_access": "Get Early Access",
    "hero.trusted": "Trusted by 10,000+ Students globally",
    "hero.title_top": "Revolutionize How",
    "hero.title_bottom": "You Absorb Knowledge",
    "hero.tagline": "Izabi is your neural companion. We transform static PDFs into interactive AI-powered laboratories. Available in English & Pidgin.",
    "hero.cta": "Initialize Learning",
    "hero.view_env": "View Environment",
    "features.title": "Everything you need to",
    "features.title_gradient": "dominate any discipline",
    "features.subtitle": "Engineered for University Scholars and secondary students mastering WAEC/UTME.",
    "how.title": "The Process",
    "how.subtitle": "Three Steps to Mastery",
    "how.step1.title": "Ingest",
    "how.step1.desc": "Feed the AI your PDFs, notes, or raw texts.",
    "how.step2.title": "Analyze",
    "how.step2.desc": "Izabi identifies key patterns and neural links.",
    "how.step3.title": "Conquer",
    "how.step3.desc": "Simulate exams and master the curriculum.",
    "pricing.title": "Invest in Your",
    "pricing.title_gradient": "Intelligence",
    "pricing.subtitle": "Simple plans. Extraordinary results.",
    "cta.upgrade": "Your Scholar Upgrade Awaits",
    "auth.login": "Scholar Portal",
    "auth.signup": "Scholar Enlistment",
    "auth.email": "Email Terminal",
    "auth.password": "Passkey",
    "auth.initialize": "Initialize Portal",
    "auth.join": "Apply for access",
    "footer.copyright": "© 2026 Izabi. All rights reserved.",
    "dashboard.greeting": "Greetings, Scholar Maestro",
    "dashboard.intro": "The Neural Laboratory is primed. Synchronize your study materials to initialize mastery protocols.",
    "dashboard.upload_title": "Document Node",
    "dashboard.upload_desc": "Upload your raw intellectual assets below.",
    "dashboard.stats_eff": "Efficiency",
    "dashboard.stats_time": "Runtime",
    "dashboard.modules_title": "Synthesis Engine",
    "dashboard.modules_ready": "Ready for Execution",
    "dashboard.modules_desc": "Select a processing module to catalyze your content",
    "dashboard.mod_summary": "Smart Summary",
    "dashboard.mod_summary_desc": "Concept Fusion",
    "dashboard.mod_quiz": "Flash Quiz",
    "dashboard.mod_quiz_desc": "Knowledge Stress Test",
    "dashboard.mod_guide": "Blueprint",
    "dashboard.mod_guide_desc": "Structural Guide",
    "dashboard.mod_flashcards": "Neural Cards",
    "dashboard.mod_flashcards_desc": "Spaced Repetition",
    "dashboard.config_title": "Module Configuration",
    "dashboard.config_desc": "Fine-tune the complexity and volume of the generated neural packets.",
    "dashboard.questions_label": "Questions:",
    "dashboard.processing": "Izabi is Processing",
    "dashboard.processing_desc": "Generating high-fidelity output...",
    "dashboard.init_node": "Initialize Node",
    "dashboard.init_desc": "Synchronize a document to access the Study Laboratory.",
    "dashboard.results_title": "Synthesis Results",
    "dashboard.res_summary": "Neural Summary",
    "dashboard.res_summary_desc": "Processed Knowledge Capsule",
    "dashboard.res_quiz": "Mastery Challenge",
    "dashboard.res_quiz_desc": "Active Synchronization Nodes",
    "dashboard.res_flashcards": "Memory Terminals",
    "dashboard.res_flashcards_desc": "Active Recall Nodes",
    "dashboard.finalize": "Initialize Finalization Protocol",
    "dashboard.mastery_confirmed": "Identity Mastery Confirmed",
    "dashboard.mastery_desc": "Neural synchronization at peak efficiency. Data yield complete.",
    "dashboard.resultant_yield": "Resultant Yield",
    "hiw.hero_tag": "System Protocol Workflow",
    "hiw.hero_title": "The Neural",
    "hiw.hero_title_span": "Protocol",
    "hiw.hero_desc": "Transitioning from raw information to total mastery in four optimized phases.",
    "hiw.ingest_title": "Data Ingestion",
    "hiw.ingest_desc": "Deploy your raw intellectual assets—PDFs, scripts, or photographic notes—into our secure ingestion terminal.",
    "hiw.ingest_d1": "Multi-node drag-and-drop",
    "hiw.ingest_d2": "Advanced OCR synchronization",
    "hiw.ingest_d3": "Instant semantic parsing",
    "hiw.ingest_d4": "Zero volumetric limits",
    "hiw.neural_title": "Neural Analysis",
    "hiw.neural_desc": "Our proprietary AI models parse your content through deep-layer semantic analysis and conceptual mapping.",
    "hiw.neural_d1": "Pattern recognition neural networks",
    "hiw.neural_d2": "Contextual link generation",
    "hiw.neural_d3": "Terminology extraction",
    "hiw.neural_d4": "Pidgin-English cross-linking",
    "hiw.synth_title": "Synthesis Output",
    "hiw.synth_desc": "Izabi transforms processed data into a suite of optimized learning modules instantly.",
    "hiw.synth_d1": "Neural summaries (Synthesis)",
    "hiw.synth_d2": "Adaptive Flash Quizzes",
    "hiw.synth_d3": "Sonic Lexicon Audio Files",
    "hiw.synth_d4": "Interactive Knowledge Maps",
    "hiw.mastery_title": "Mastery Deployment",
    "hiw.mastery_desc": "Engage with the generated laboratory environment to verify knowledge retention and academic dominance.",
    "hiw.mastery_d1": "Competitive Scholar Duels",
    "hiw.mastery_d2": "Readiness analytics tracking",
    "hiw.mastery_d3": "Global leaderboards",
    "hiw.mastery_d4": "Sync to any mobile node",
    "hiw.lat_setup": "Account Setup",
    "hiw.lat_upload": "Data Upload",
    "hiw.lat_neural": "Neural Process",
    "hiw.lat_mastery": "Total Mastery",
    "hiw.cta_title": "Ready to initiate the \nIzabi protocol?",
    "hiw.cta_btn": "Initialize Enlistment",
  },
  pidgin: {
    "nav.features": "Wetin We Get",
    "nav.how_it_works": "How E De Work",
    "nav.pricing": "Price List",
    "nav.about": "About Us",
    "nav.client_portal": "Student Corner",
    "nav.get_started": "Start Now",
    "nav.get_early_access": "Enter Early",
    "hero.trusted": "More than 10,000 students don join us",
    "hero.title_top": "Change The Way",
    "hero.title_bottom": "You De Carry Book",
    "hero.tagline": "Izabi na your personal sabi-person. We turn your PDFs to serious AI lab. We sabi English and Pidgin.",
    "hero.cta": "Start Learning",
    "hero.view_env": "See How E Be",
    "features.title": "Everything wey you need",
    "features.title_gradient": "make you sabi every book",
    "features.subtitle": "We build am for University and Secondary school people wey wan pass WAEC/JAMB.",
    "how.title": "How We De Do Am",
    "how.subtitle": "Three Steps to Master Am",
    "how.step1.title": "Put Am",
    "how.step1.desc": "Give the AI your PDFs, notes, or anything you wan read.",
    "how.step2.title": "Check Am",
    "how.step2.desc": "Izabi go check all the patterns and link them together.",
    "how.step3.title": "Win Am",
    "how.step3.desc": "Practice exam and master everything finish.",
    "pricing.title": "Invest in Your",
    "pricing.title_gradient": "Brain",
    "pricing.subtitle": "Better plans. Better results for you.",
    "cta.upgrade": "Your Scholar Upgrade Don Ready",
    "auth.login": "Student Corner",
    "auth.signup": "Join Us",
    "auth.email": "Email Terminal",
    "auth.password": "Password",
    "auth.initialize": "Open Portal",
    "auth.join": "Sign Up Here",
    "footer.copyright": "© 2026 Izabi. No shaking.",
    "dashboard.greeting": "How far, Scholar Boss",
    "dashboard.intro": "The lab don set. Oya put your material make we start to cook am.",
    "dashboard.upload_title": "Document Base",
    "dashboard.upload_desc": "Drop your file here make we reason am.",
    "dashboard.stats_eff": "Speed Level",
    "dashboard.stats_time": "Time Spent",
    "dashboard.modules_title": "Cooking Engine",
    "dashboard.modules_ready": "We Don Ready",
    "dashboard.modules_desc": "Choose wetin you want make we do with your book",
    "dashboard.mod_summary": "Sharp Summary",
    "dashboard.mod_summary_desc": "Join am together",
    "dashboard.mod_quiz": "Sharp Quiz",
    "dashboard.mod_quiz_desc": "Test your brain",
    "dashboard.mod_guide": "Study Guide",
    "dashboard.mod_guide_desc": "Roadmap to pass",
    "dashboard.mod_flashcards": "Memory Cards",
    "dashboard.mod_flashcards_desc": "Recall am fast",
    "dashboard.config_title": "Set Am Well",
    "dashboard.config_desc": "Arrange how you want make e heavy reach.",
    "dashboard.questions_label": "How Many:",
    "dashboard.processing": "Izabi De Cook",
    "dashboard.processing_desc": "Abeg wait small, e de load...",
    "dashboard.init_node": "Start Engine",
    "dashboard.init_desc": "Put file first before we fit start.",
    "dashboard.results_title": "Wetin We Cook",
    "dashboard.res_summary": "The Main Point",
    "dashboard.res_summary_desc": "Wetin the book talk",
    "dashboard.res_quiz": "Face Your Fears",
    "dashboard.res_quiz_desc": "Questions wey go test you",
    "dashboard.res_flashcards": "Brain Cards",
    "dashboard.res_flashcards_desc": "Memory sharp points",
    "dashboard.finalize": "Submit Everything",
    "dashboard.mastery_confirmed": "You Too Sabi",
    "dashboard.mastery_desc": "Your brain don sharp. Everything clear.",
    "dashboard.resultant_yield": "You Too Sabi",
    "dashboard.result_score": "Your Score",
    "hiw.hero_tag": "How E De Waka",
    "hiw.hero_title": "The Neural",
    "hiw.hero_title_span": "Way",
    "hiw.hero_desc": "How we take move from raw info enter full master-level in four sharp steps.",
    "hiw.ingest_title": "Load Am",
    "hiw.ingest_desc": "Put your PDFs, notes, or pictures inside our secure engine.",
    "hiw.ingest_d1": "Drag and drop plenty files",
    "hiw.ingest_d2": "Scan everything sharp",
    "hiw.ingest_d3": "Understand am one time",
    "hiw.ingest_d4": "No limit to size",
    "hiw.neural_title": "Check Am",
    "hiw.neural_desc": "Our AI go check your book well well see wetin dey inside.",
    "hiw.neural_d1": "AI wey sabi book",
    "hiw.neural_d2": "Link everything together",
    "hiw.neural_d3": "Pick important words",
    "hiw.neural_d4": "Pidgin & English mix",
    "hiw.synth_title": "Result Output",
    "hiw.synth_desc": "Izabi go turn your data to better reading material one time.",
    "hiw.synth_d1": "Smart Summaries",
    "hiw.synth_d2": "Sharp Quizzes",
    "hiw.synth_d3": "Audio Dictionary",
    "hiw.synth_d4": "Mind Maps",
    "hiw.mastery_title": "Master Am",
    "hiw.mastery_desc": "Use the lab verify say you truly sabi book.",
    "hiw.mastery_d1": "Challenge Scholars",
    "hiw.mastery_d2": "Check your level",
    "hiw.mastery_d3": "World Ranking",
    "hiw.mastery_d4": "Any phone fit carry am",
    "hiw.lat_setup": "Setup",
    "hiw.lat_upload": "Upload",
    "hiw.lat_neural": "Process",
    "hiw.lat_mastery": "Sabi",
    "hiw.cta_title": "You ready to start \nthe Izabi way?",
    "hiw.cta_btn": "Join Us Now",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(
    () => (localStorage.getItem("izabi-lang") as Language) || "en"
  )

  const setLanguage = (lang: Language) => {
    localStorage.setItem("izabi-lang", lang)
    setLanguageState(lang)
  }

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
