import { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'pidgin' | 'igbo' | 'yoruba' | 'hausa';

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.features': 'Features',
        'nav.how_it_works': 'How It Works',
        'nav.pricing': 'Pricing',
        'nav.about': 'About',
        'nav.client_portal': 'Login',
        'nav.get_started': 'Create Account',
        'nav.get_early_access': 'Get Early Access',
        'hero.trusted': 'Trusted by 10,000+ Students globally',
        'hero.title_top': 'Revolutionize How',
        'hero.title_bottom': 'You Absorb Knowledge',
        'hero.tagline':
            'Izabi is your smart study companion. We transform static PDFs into interactive AI-powered study tools. Available in English & Pidgin.',
        'hero.cta': 'Create Account',
        'hero.view_env': 'View Environment',
        'features.title': 'Everything you need to',
        'features.title_gradient': 'dominate any discipline',
        'features.subtitle':
            'Engineered for University Scholars and secondary students mastering WAEC/UTME.',
        'how.title': 'The Process',
        'how.subtitle': 'Three Steps to Mastery',
        'how.step1.title': 'Upload',
        'how.step1.desc': 'Upload your PDFs, notes, or raw texts.',
        'how.step2.title': 'Analyze',
        'how.step2.desc': 'Izabi identifies key patterns and connections.',
        'how.step3.title': 'Master',
        'how.step3.desc': 'Simulate exams and master the curriculum.',
        'pricing.title': 'Invest in Your',
        'pricing.title_gradient': 'Intelligence',
        'pricing.subtitle': 'Simple plans. Extraordinary results.',
        'cta.upgrade': 'Your Scholar Upgrade Awaits',
        'cta.tagline':
            'Join thousands of students and revolutionize your learning experience today.',
        'auth.login': 'Student Login',
        'auth.signup': 'Create Account',
        'auth.email': 'Email Address',
        'auth.password': 'Password',
        'auth.initialize': 'Sign In',
        'auth.join': 'Apply for access',
        'footer.copyright': '© 2026 Izabi. All rights reserved.',
        'dashboard.greeting': 'Welcome back,',
        'dashboard.intro':
            'Your study space is ready. Upload materials to start learning.',
        'dashboard.upload_title': 'UPLOAD DOCUMENT',
        'dashboard.upload_desc': 'Upload your notes or textbooks here.',
        'dashboard.stats_eff': 'Study Speed',
        'dashboard.stats_time': 'Study Time',
        'dashboard.modules_title': 'STUDY TOOLS',
        'dashboard.modules_ready': 'READY',
        'dashboard.modules_desc': 'Choose a tool to help you study.',
        'dashboard.mod_summary': 'Summary',
        'dashboard.mod_summary_desc': 'Quick Overview',
        'dashboard.mod_quiz': 'Quiz',
        'dashboard.mod_quiz_desc': 'Test Yourself',
        'dashboard.mod_guide': 'Study Guide',
        'dashboard.mod_guide_desc': 'Step-by-step Plan',
        'dashboard.mod_flashcards': 'Flashcards',
        'dashboard.mod_flashcards_desc': 'Memory Aids',
        'dashboard.config_title': 'SETTINGS',
        'dashboard.config_desc': 'Adjust the settings for your result.',
        'dashboard.questions_label': 'Questions:',
        'dashboard.processing': 'PROCESSING...',
        'dashboard.processing_desc': 'Generating your study materials...',
        'dashboard.init_node': 'Study Setup',
        'dashboard.init_desc': 'Upload a document to use the tools.',
        'dashboard.results_title': 'YOUR RESULTS',
        'dashboard.res_summary': 'Summary',
        'dashboard.res_summary_desc': 'Key Points',
        'dashboard.res_quiz': 'Quiz',
        'dashboard.res_quiz_desc': 'Practice Questions',
        'dashboard.res_flashcards': 'Flashcards',
        'dashboard.res_flashcards_desc': 'Memory Aids',
        'dashboard.finalize': 'COMPLETE',
        'dashboard.mastery_confirmed': 'Quiz Complete',
        'dashboard.mastery_desc': "You've finished the quiz.",
        'dashboard.resultant_yield': 'Your Check',
        'hiw.hero_tag': 'How It Works',
        'hiw.hero_title': 'The Study',
        'hiw.hero_title_span': 'Process',
        'hiw.hero_desc':
            'Transitioning from raw information to total mastery in four simple steps.',
        'hiw.ingest_title': 'Upload',
        'hiw.ingest_desc': 'Upload your documents securely.',
        'hiw.ingest_d1': 'Easy drag-and-drop',
        'hiw.ingest_d2': 'Advanced text recognition',
        'hiw.ingest_d3': 'Instant understanding',
        'hiw.ingest_d4': 'No size limits',
        'hiw.neural_title': 'Smart Analysis',
        'hiw.neural_desc':
            'Our AI analyzes your content to understand the key concepts.',
        'hiw.neural_d1': 'Smart pattern recognition',
        'hiw.neural_d2': 'Contextual connections',
        'hiw.neural_d3': 'Key term extraction',
        'hiw.neural_d4': 'Cross-language support',
        'hiw.synth_title': 'Generate Materials',
        'hiw.synth_desc':
            'Izabi transforms your data into study materials instantly.',
        'hiw.synth_d1': 'Smart Summaries',
        'hiw.synth_d2': 'Practice Quizzes',
        'hiw.synth_d3': 'Audio Lessons',
        'hiw.synth_d4': 'Knowledge Maps',
        'hiw.mastery_title': 'Test Knowledge',
        'hiw.mastery_desc':
            'Use the generated materials to verify your knowledge and success.',
        'hiw.mastery_d1': 'Challenge Friends',
        'hiw.mastery_d2': 'Track Progress',
        'hiw.mastery_d3': 'Global Leaderboards',
        'hiw.mastery_d4': 'Mobile Access',
        'hiw.lat_setup': 'Setup',
        'hiw.lat_upload': 'Upload',
        'hiw.lat_neural': 'Process',
        'hiw.lat_mastery': 'Success',
        'hiw.cta_title': 'Ready to start \nlearning with Izabi?',
        'hiw.cta_btn': 'Create Account',
    },
    pidgin: {
        'nav.features': 'Wetin We Get',
        'nav.how_it_works': 'How E De Work',
        'nav.pricing': 'Price List',
        'nav.about': 'About Us',
        'nav.client_portal': 'Login',
        'nav.get_started': 'Create Account',
        'nav.get_early_access': 'Enter Early',
        'hero.trusted': 'More than 10,000 students don join us',
        'hero.title_top': 'Change The Way',
        'hero.title_bottom': 'You De Carry Book',
        'hero.tagline':
            'Izabi na your personal sabi-person. We turn your PDFs to serious AI lab. We sabi English and Pidgin.',
        'hero.cta': 'Create Account',
        'hero.view_env': 'See How E Be',
        'features.title': 'Everything wey you need',
        'features.title_gradient': 'make you sabi every book',
        'features.subtitle':
            'We build am for University and Secondary school people wey wan pass WAEC/JAMB.',
        'how.title': 'How We De Do Am',
        'how.subtitle': 'Three Steps to Master Am',
        'how.step1.title': 'Put Am',
        'how.step1.desc':
            'Give the AI your PDFs, notes, or anything you wan read.',
        'how.step2.title': 'Check Am',
        'how.step2.desc':
            'Izabi go check all the patterns and link them together.',
        'how.step3.title': 'Win Am',
        'how.step3.desc': 'Practice exam and master everything finish.',
        'pricing.title': 'Invest in Your',
        'pricing.title_gradient': 'Brain',
        'pricing.subtitle': 'Better plans. Better results for you.',
        'cta.upgrade': 'Your Scholar Upgrade Don Ready',
        'cta.tagline':
            'Join plenty students and change how you de read book today.',
        'auth.login': 'Student Corner',
        'auth.signup': 'Join Us',
        'auth.email': 'Email Terminal',
        'auth.password': 'Password',
        'auth.initialize': 'Open Portal',
        'auth.join': 'Sign Up Here',
        'footer.copyright': '© 2026 Izabi. No shaking.',
        'dashboard.greeting': 'How far, Scholar Boss',
        'dashboard.intro':
            'The lab don set. Oya put your material make we start to cook am.',
        'dashboard.upload_title': 'Document Base',
        'dashboard.upload_desc': 'Drop your file here make we reason am.',
        'dashboard.stats_eff': 'Speed Level',
        'dashboard.stats_time': 'Time Spent',
        'dashboard.modules_title': 'Cooking Engine',
        'dashboard.modules_ready': 'We Don Ready',
        'dashboard.modules_desc':
            'Choose wetin you want make we do with your book',
        'dashboard.mod_summary': 'Sharp Summary',
        'dashboard.mod_summary_desc': 'Join am together',
        'dashboard.mod_quiz': 'Sharp Quiz',
        'dashboard.mod_quiz_desc': 'Test your brain',
        'dashboard.mod_guide': 'Study Guide',
        'dashboard.mod_guide_desc': 'Roadmap to pass',
        'dashboard.mod_flashcards': 'Memory Cards',
        'dashboard.mod_flashcards_desc': 'Recall am fast',
        'dashboard.config_title': 'Set Am Well',
        'dashboard.config_desc': 'Arrange how you want make e heavy reach.',
        'dashboard.questions_label': 'How Many:',
        'dashboard.processing': 'Izabi De Cook',
        'dashboard.processing_desc': 'Abeg wait small, e de load...',
        'dashboard.init_node': 'Study Setup',
        'dashboard.init_desc': 'Put file first before we fit start.',
        'dashboard.results_title': 'Wetin We Cook',
        'dashboard.res_summary': 'The Main Point',
        'dashboard.res_summary_desc': 'Wetin the book talk',
        'dashboard.res_quiz': 'Face Your Fears',
        'dashboard.res_quiz_desc': 'Questions wey go test you',
        'dashboard.res_flashcards': 'Brain Cards',
        'dashboard.res_flashcards_desc': 'Memory sharp points',
        'dashboard.finalize': 'Submit Everything',
        'dashboard.mastery_confirmed': 'You Too Sabi',
        'dashboard.mastery_desc': 'Your brain don sharp. Everything clear.',
        'dashboard.resultant_yield': 'You Too Sabi',
        'dashboard.result_score': 'Your Score',
        'hiw.hero_tag': 'How E De Waka',
        'hiw.hero_title': 'The Neural',
        'hiw.hero_title_span': 'Way',
        'hiw.hero_desc':
            'How we take move from raw info enter full master-level in four sharp steps.',
        'hiw.ingest_title': 'Load Am',
        'hiw.ingest_desc':
            'Put your PDFs, notes, or pictures inside our secure engine.',
        'hiw.ingest_d1': 'Drag and drop plenty files',
        'hiw.ingest_d2': 'Scan everything sharp',
        'hiw.ingest_d3': 'Understand am one time',
        'hiw.ingest_d4': 'No limit to size',
        'hiw.neural_title': 'Check Am',
        'hiw.neural_desc':
            'Our AI go check your book well well see wetin dey inside.',
        'hiw.neural_d1': 'AI wey sabi book',
        'hiw.neural_d2': 'Link everything together',
        'hiw.neural_d3': 'Pick important words',
        'hiw.neural_d4': 'Pidgin & English mix',
        'hiw.synth_title': 'Result Output',
        'hiw.synth_desc':
            'Izabi go turn your data to better reading material one time.',
        'hiw.synth_d1': 'Smart Summaries',
        'hiw.synth_d2': 'Sharp Quizzes',
        'hiw.synth_d3': 'Audio Dictionary',
        'hiw.synth_d4': 'Mind Maps',
        'hiw.mastery_title': 'Master Am',
        'hiw.mastery_desc': 'Use the lab verify say you truly sabi book.',
        'hiw.mastery_d1': 'Challenge Scholars',
        'hiw.mastery_d2': 'Check your level',
        'hiw.mastery_d3': 'World Ranking',
        'hiw.mastery_d4': 'Any phone fit carry am',
        'hiw.lat_setup': 'Setup',
        'hiw.lat_upload': 'Upload',
        'hiw.lat_neural': 'Process',
        'hiw.lat_mastery': 'Sabi',
        'hiw.cta_title': 'You ready to start \nthe Izabi way?',
        'hiw.cta_btn': 'Create Account',
    },
    igbo: {
        'nav.features': 'Atụmatụ',
        'nav.how_it_works': 'Ka O Si Arụ Ọrụ',
        'nav.pricing': 'Ọnụ Ahịa',
        'nav.about': 'Banyere Anyị',
        'nav.client_portal': 'Banye',
        'nav.get_started': 'Mepụta Akaụntụ',
        'nav.get_early_access': 'Banye Oge Mbụ',
        'hero.trusted': 'Ndị mmụta karịrị puku iri tụkwasịrị anyị obi',
        'hero.title_top': 'Gbanwee Etu I Si',
        'hero.title_bottom': 'Amụ Ihe',
        'hero.tagline':
            "Izabi bụ onye enyemaka mmụta gị. Anyị na-agbanwe PDF gị ka ọ bụrụ ngwa mmụta AI. Dị n'asụsụ Igbo.",
        'hero.cta': 'Mepụta Akaụntụ',
        'hero.view_env': 'Lee Gburugburu',
        'features.title': 'Ihe niile ị chọrọ',
        'features.title_gradient': 'iji mụta ihe ọ bụla',
        'features.subtitle':
            'Emere ya maka ụmụ akwụkwọ Mahadum na Secondary na-akwado WAEC/UTME.',
        'how.title': 'Usoro Ya',
        'how.subtitle': 'Nzọụkwụ Atọ Iji Mụta',
        'how.step1.title': 'Bugote',
        'how.step1.desc': 'Bugote PDF, ndetu, ma ọ bụ ederede gị.',
        'how.step2.title': 'Nyochaa',
        'how.step2.desc': 'Izabi na-achọpụta isi ihe na njikọ dị mkpa.',
        'how.step3.title': 'Mụta',
        'how.step3.desc': 'Mụọ ajụjụ ule ma ghọta ihe ọmụmụ ahụ nke ọma.',
        'pricing.title': 'Tinye Ego Na',
        'pricing.title_gradient': 'Ọgụgụ Isi Gị',
        'pricing.subtitle': 'Atụmatụ dị mfe. Nsonaazụ pụrụ iche.',
        'cta.upgrade': 'Nkwalite Mmụta Gị Dị Njikere',
        'cta.tagline':
            'Sonyere puku kwuru puku ụmụ akwụkwọ ma gbanwee ahụmịhe mmụta gị taa.',
        'auth.login': 'Banye',
        'auth.signup': 'Debanye Aha',
        'auth.email': 'Adreesị Email',
        'auth.password': 'Okwuntughe',
        'auth.initialize': 'Banye',
        'auth.join': 'Debanye Aha',
        'footer.copyright': '© 2026 Izabi. Ikike niile echekwabara.',
        'dashboard.greeting': 'Nnọọ,',
        'dashboard.intro':
            'Ebe ọmụmụ gị dị njikere. Bugote ihe iji malite ịmụ ihe.',
        'dashboard.upload_title': 'BUGOTE AKWỤKWỌ',
        'dashboard.upload_desc': 'Bugote ndetu ma ọ bụ akwụkwọ ọgụgụ gị ebe a.',
        'dashboard.stats_eff': 'Ọsọ Mmụta',
        'dashboard.stats_time': 'Oge Ejiri Mụọ Ihe',
        'dashboard.modules_title': 'NGWA MMỤTA',
        'dashboard.modules_ready': 'DỊ NJIKERE',
        'dashboard.modules_desc': 'Họrọ ngwa ga-enyere gị aka ịmụ ihe.',
        'dashboard.mod_summary': 'Nchịkọta',
        'dashboard.mod_summary_desc': 'Nlele Ngwa Ngwa',
        'dashboard.mod_quiz': 'Ajụjụ',
        'dashboard.mod_quiz_desc': 'Nwalee Onwe Gị',
        'dashboard.mod_guide': 'Nduzi Ọmụmụ',
        'dashboard.mod_guide_desc': 'Atụmatụ Nzọụkwụ site na Nzọụkwụ',
        'dashboard.mod_flashcards': 'Flashcards',
        'dashboard.mod_flashcards_desc': 'Enyemaka Ncheta',
        'dashboard.config_title': 'NHAZI',
        'dashboard.config_desc': 'Hazie nsonaazụ gị.',
        'dashboard.questions_label': 'Ajụjụ:',
        'dashboard.processing': 'NA-ARỤ ỌRỤ...',
        'dashboard.processing_desc': 'Na-emepụta ihe ọmụmụ gị...',
        'dashboard.init_node': 'Nhazi Ọmụmụ',
        'dashboard.init_desc': 'Bugote akwụkwọ iji jiri ngwa ọrụ ndị a.',
        'dashboard.results_title': 'NSONAAZỤ GỊ',
        'dashboard.res_summary': 'Nchịkọta',
        'dashboard.res_summary_desc': 'Isi Ihe',
        'dashboard.res_quiz': 'Ajụjụ',
        'dashboard.res_quiz_desc': 'Ajụjụ Nlele',
        'dashboard.res_flashcards': 'Flashcards',
        'dashboard.res_flashcards_desc': 'Enyemaka Ncheta',
        'dashboard.finalize': 'MECHA',
        'dashboard.mastery_confirmed': 'Ajụjụ Ezuola',
        'dashboard.mastery_desc': 'Ị gụchara ajụjụ a.',
        'dashboard.resultant_yield': 'Nsonaazụ Gị',
        'hiw.hero_tag': 'Ka O Si Arụ Ọrụ',
        'hiw.hero_title': 'Usoro',
        'hiw.hero_title_span': 'Ọmụmụ',
        'hiw.hero_desc':
            'Si na ozi nkịtị gaa na nghọta zuru oke na nzọụkwụ anọ dị mfe.',
        'hiw.ingest_title': 'Bugote',
        'hiw.ingest_desc': 'Bugote PDF, ndetu, ma ọ bụ foto gị.',
        'hiw.ingest_d1': 'Dọrọ ma tụnye',
        'hiw.ingest_d2': 'Njirimara ederede dị elu',
        'hiw.ingest_d3': 'Nghọta ozugbo',
        'hiw.ingest_d4': 'Enweghị oke nha',
        'hiw.neural_title': 'Nyocha Smart',
        'hiw.neural_desc': 'AI anyị na-enyocha ọdịnaya gị iji ghọta isi ihe.',
        'hiw.neural_d1': 'Nchọpụta ụkpụrụ',
        'hiw.neural_d2': 'Njikọ gbara ya gburugburu',
        'hiw.neural_d3': 'Mwepụta isi okwu',
        'hiw.neural_d4': 'Nkwado asụsụ dị iche iche',
        'hiw.synth_title': 'Mepụta Agụmakwụkwọ',
        'hiw.synth_desc':
            'Izabi na-agbanwe data gị ka ọ bụrụ ihe ọmụmụ ozugbo.',
        'hiw.synth_d1': 'Nchịkọta Smart',
        'hiw.synth_d2': 'Ajụjụ Nlele',
        'hiw.synth_d3': 'Nkuzi Audio',
        'hiw.synth_d4': 'Map Ọmụma',
        'hiw.mastery_title': 'Nwalee Ọmụma',
        'hiw.mastery_desc': 'Jiri ihe ọmụmụ ndị a nwalee ihe ị mụtara.',
        'hiw.mastery_d1': 'Ma aka ndị enyi',
        'hiw.mastery_d2': 'Lelee Ọganiru',
        'hiw.mastery_d3': 'Ọkwa Ụwa',
        'hiw.mastery_d4': 'Nweta na ekwentị',
        'hiw.lat_setup': 'Nhazi',
        'hiw.lat_upload': 'Bugote',
        'hiw.lat_neural': 'Usoro',
        'hiw.lat_mastery': 'Mmeri',
        'hiw.cta_title': 'Dị njikere ịmalite \nịmụ ihe na Izabi?',
        'hiw.cta_btn': 'Mepụta Akaụntụ',
    },
    yoruba: {
        'nav.features': 'Awọn Ẹya',
        'nav.how_it_works': 'Bi O Ṣe N Ṣiṣẹ',
        'nav.pricing': 'Iye Owo',
        'nav.about': 'Nipa Wa',
        'nav.client_portal': 'Wọle',
        'nav.get_started': 'Ṣẹda Akanti',
        'nav.get_early_access': 'Wọle Ni Tete',
        'hero.trusted': 'Awọn ọmọ ile-iwe to ju 10,000 lọ gbẹkẹle wa',
        'hero.title_top': 'Yi Bi O Ṣe',
        'hero.title_bottom': 'Kọ Ẹkọ Pada',
        'hero.tagline':
            'Izabi jẹ ọrẹ ẹkọ ti oye rẹ. A n yi awọn PDF pada si awọn irinṣẹ ẹkọ AI ibaraenisepo. Wa ni Yoruba.',
        'hero.cta': 'Ṣẹda Akanti',
        'hero.view_env': 'Wo Ayika',
        'features.title': 'Ohun gbogbo ti o nilo lati',
        'features.title_gradient': 'kọ ẹkọ eyikeyi',
        'features.subtitle':
            'A ṣe apẹrẹ fun awọn ọmọ ile-iwe giga ati ile-iwe keji ti n mura fun WAEC/UTME.',
        'how.title': 'Ilana Naa',
        'how.subtitle': 'Awọn Igbesẹ Meta si Aṣeyọri',
        'how.step1.title': 'Gbe Wọle',
        'how.step1.desc': 'Gbe awọn PDF, awọn akọsilẹ, tabi awọn ọrọ rẹ wọle.',
        'how.step2.title': 'Ṣe Itupalẹ',
        'how.step2.desc':
            'Izabi n ṣe idanimọ awọn ilana pataki ati awọn asopọ.',
        'how.step3.title': 'Kọ Ẹkọ',
        'how.step3.desc': 'Ṣe idanwo ati kọ ẹkọ naa daradara.',
        'pricing.title': 'Ṣe Idoko-owo Ni',
        'pricing.title_gradient': 'Oye Rẹ',
        'pricing.subtitle': 'Awọn eto ti o rọrun. Awọn abajade alailẹgbẹ.',
        'cta.upgrade': 'Igbega Akeko Rẹ N Duro',
        'cta.tagline':
            'Darapọ mọ ẹgbẹẹgbẹrun awọn ọmọ ile-iwe ki o yi iriri ẹkọ rẹ pada loni.',
        'auth.login': 'Wọle Akeko',
        'auth.signup': 'Ṣẹda Akọọlẹ',
        'auth.email': 'Adirẹsi Imeeli',
        'auth.password': 'Ọrọ igbaniwọle',
        'auth.initialize': 'Wọle',
        'auth.join': 'Waye fun iraye si',
        'footer.copyright': '© 2026 Izabi. Gbogbo ẹtọ wa ni ipamọ.',
        'dashboard.greeting': 'Kaabo pada,',
        'dashboard.intro':
            'Aye ẹkọ rẹ ti ṣetan. Gbe awọn ohun elo wọle lati bẹrẹ ẹkọ.',
        'dashboard.upload_title': 'GBE AKỌSILẸ WỌLE',
        'dashboard.upload_desc':
            'Gbe awọn akọsilẹ tabi awọn iwe-ẹkọ rẹ wọle nibi.',
        'dashboard.stats_eff': 'Iyara Ẹkọ',
        'dashboard.stats_time': 'Akoko Ẹkọ',
        'dashboard.modules_title': 'AWỌN IRINṢẸ ẸKỌ',
        'dashboard.modules_ready': 'ṢETAN',
        'dashboard.modules_desc':
            'Yan irinṣẹ kan lati ṣe iranlọwọ fun ọ lati kọ ẹkọ.',
        'dashboard.mod_summary': 'Akopọ',
        'dashboard.mod_summary_desc': 'Akopọ Yara',
        'dashboard.mod_quiz': 'Idanwo',
        'dashboard.mod_quiz_desc': 'Dan Ara Rẹ Wo',
        'dashboard.mod_guide': 'Itọsọna Ẹkọ',
        'dashboard.mod_guide_desc': 'Eto Igbesẹ-nipasẹ-Igbesẹ',
        'dashboard.mod_flashcards': 'Flashcards',
        'dashboard.mod_flashcards_desc': 'Iranlọwọ Iranti',
        'dashboard.config_title': 'Eto',
        'dashboard.config_desc': 'Ṣatunṣe awọn eto fun abajade rẹ.',
        'dashboard.questions_label': 'Awọn ibeere:',
        'dashboard.processing': 'N ṢIṢẸ...',
        'dashboard.processing_desc': 'N ṣe ipilẹṣẹ awọn ohun elo ikẹkọ rẹ...',
        'dashboard.init_node': 'Eto Ẹkọ',
        'dashboard.init_desc': 'Gbe iwe kan wọle lati lo awọn irinṣẹ.',
        'dashboard.results_title': 'WỌN WA NI ABẸRẸ RE',
        'dashboard.res_summary': 'Akopọ',
        'dashboard.res_summary_desc': 'Awọn Ojuami Pataki',
        'dashboard.res_quiz': 'Idanwo',
        'dashboard.res_quiz_desc': 'Awọn Ibeere Didara',
        'dashboard.res_flashcards': 'Flashcards',
        'dashboard.res_flashcards_desc': 'Iranlọwọ Iranti',
        'dashboard.finalize': 'PARI',
        'dashboard.mastery_confirmed': 'Idanwo Pari',
        'dashboard.mastery_desc': 'O ti pari idanwo naa.',
        'dashboard.resultant_yield': 'Ayẹwo Rẹ',
        'hiw.hero_tag': 'Bi O Ṣe N Ṣiṣẹ',
        'hiw.hero_title': 'Ilana',
        'hiw.hero_title_span': 'Ẹkọ',
        'hiw.hero_desc':
            'Gbigbe lati alaye lasan si oye pipe ni awọn igbesẹ mẹrin ti o rọrun.',
        'hiw.ingest_title': 'Gbe Wọle',
        'hiw.ingest_desc':
            'Gbe awọn PDF, awọn akọsilẹ, tabi awọn aworan rẹ wọle.',
        'hiw.ingest_d1': 'Fa ati ju silẹ',
        'hiw.ingest_d2': 'Idanimọ ọrọ to ti ni ilọsiwaju',
        'hiw.ingest_d3': 'Oye lẹsẹkẹsẹ',
        'hiw.ingest_d4': 'Ko si opin iwọn',
        'hiw.neural_title': 'Itupalẹ Smart',
        'hiw.neural_desc':
            'AI wa n ṣe itupalẹ akoonu rẹ lati loye awọn imọran pataki.',
        'hiw.neural_d1': 'Idanimọ ilana',
        'hiw.neural_d2': 'Awọn isopọ ọrọ',
        'hiw.neural_d3': 'Iyalo ọrọ pataki',
        'hiw.neural_d4': 'Atilẹyin ede agbarke',
        'hiw.synth_title': 'Ṣe Ipilẹṣẹ Ohun elo',
        'hiw.synth_desc':
            'Izabi yi data rẹ pada si awọn ohun elo ikẹkọ lẹsẹkẹsẹ.',
        'hiw.synth_d1': 'Awọn Akopọ Smart',
        'hiw.synth_d2': 'Awọn Idanwo Didara',
        'hiw.synth_d3': 'Awọn Ẹkọ Audio',
        'hiw.synth_d4': 'Awọn Maapu Imọ',
        'hiw.mastery_title': 'Dan Imọ Wo',
        'hiw.mastery_desc': 'Lo awọn ohun elo ti ipilẹṣẹ lati jẹrisi imọ rẹ.',
        'hiw.mastery_d1': 'Koju Awọn Ọrẹ',
        'hiw.mastery_d2': 'Tọpinpin Ilọsiwaju',
        'hiw.mastery_d3': 'Ipo Agbaye',
        'hiw.mastery_d4': 'Wiwọle Alagbeka',
        'hiw.lat_setup': 'Eto',
        'hiw.lat_upload': 'Gbe Wọle',
        'hiw.lat_neural': 'Ilana',
        'hiw.lat_mastery': 'Aṣeyọri',
        'hiw.cta_title': 'Ṣe o ṣetan lati bẹrẹ \nkikọ pẹlu Izabi?',
        'hiw.cta_btn': 'Ṣẹda Akanti',
    },
    hausa: {
        'nav.features': 'Siffofi',
        'nav.how_it_works': 'Yadda Yake Aiki',
        'nav.pricing': 'Farashi',
        'nav.about': 'Game da Mu',
        'nav.client_portal': 'Shiga',
        'nav.get_started': 'Kirkiri Asusun',
        'nav.get_early_access': 'Samu Dama da Wuri',
        'hero.trusted': 'Dalibai sama da 10,000 sun amince da mu',
        'hero.title_top': 'Sauya Yadda Kake',
        'hero.title_bottom': 'Koyan Karatu',
        'hero.tagline':
            'Izabi abokin karatun ku ne na zamani. Muna canza PDFs zuwa kayan aikin karatu na AI. Akwai cikin Hausa.',
        'hero.cta': 'Kirkiri Asusun',
        'hero.view_env': 'Duba Muhalli',
        'features.title': 'Duk abin da kuke buƙata don',
        'features.title_gradient': 'ƙwarewa a kowane fanni',
        'features.subtitle':
            "An tsara shi don ɗaliban jami'a da sakandare suna shirin WAEC/UTME.",
        'how.title': 'Tsarin',
        'how.subtitle': 'Matakai Uku zuwa Ƙwarewa',
        'how.step1.title': 'Loda',
        'how.step1.desc': 'Loda PDFs ɗinku, bayanai, ko rubutun da kuke so.',
        'how.step2.title': 'Bincika',
        'how.step2.desc': 'Izabi yana gano mahimman alamu da haɗin kai.',
        'how.step3.title': 'Ƙware',
        'how.step3.desc': 'Yi gwajin karatu kuma ku ƙware manhaja.',
        'pricing.title': 'Zuba Jari a',
        'pricing.title_gradient': 'Hankalinku',
        'pricing.subtitle': 'Tsare-tsare masu sauƙi. Sakamako na musamman.',
        'cta.upgrade': 'Haɓaka Karatunku Yana Jira',
        'cta.tagline':
            'Haɗa dubbannin ɗalibai kuma ku sauya fasalin karatun ku a yau.',
        'auth.login': 'Shiga Dalibai',
        'auth.signup': 'Bude Asusun',
        'auth.email': 'Adireshin Imel',
        'auth.password': 'Kalmar Sirri',
        'auth.initialize': 'Shiga',
        'auth.join': 'Nemi dama',
        'footer.copyright': '© 2026 Izabi. An kiyaye duk haƙƙoƙi.',
        'dashboard.greeting': 'Barka da dawowa,',
        'dashboard.intro':
            'Wurin karatun ku yana shirye. Loda kayan aiki don fara karatu.',
        'dashboard.upload_title': 'LODA RUBUTU',
        'dashboard.upload_desc': 'Loda bayanan karatun ku ko littattafai anan.',
        'dashboard.stats_eff': 'Gudun Karatu',
        'dashboard.stats_time': 'Lokacin Karatu',
        'dashboard.modules_title': 'KAYAN KARATU',
        'dashboard.modules_ready': 'SHIRYE',
        'dashboard.modules_desc': 'Zaɓi kayan aiki don taimaka muku karatu.',
        'dashboard.mod_summary': 'Takaitawa',
        'dashboard.mod_summary_desc': 'Dubawa da Sauri',
        'dashboard.mod_quiz': 'Gwaji',
        'dashboard.mod_quiz_desc': 'Gwada Kanku',
        'dashboard.mod_guide': 'Jagoran Karatu',
        'dashboard.mod_guide_desc': 'Tsarin Mataki-Mataki',
        'dashboard.mod_flashcards': 'Flashcards',
        'dashboard.mod_flashcards_desc': 'Taimakon Tunawa',
        'dashboard.config_title': 'SAITAWA',
        'dashboard.config_desc': 'Daidaita saituna don sakamakon ku.',
        'dashboard.questions_label': 'Tambayoyi:',
        'dashboard.processing': 'ANA AIKI...',
        'dashboard.processing_desc': 'Yana haifar da kayan karatun ku...',
        'dashboard.init_node': 'Tsarin Karatu',
        'dashboard.init_desc': 'Loda takarda don amfani da kayan aiki.',
        'dashboard.results_title': 'SAKAMAKON KU',
        'dashboard.res_summary': 'Takaitawa',
        'dashboard.res_summary_desc': 'Mahimman Bayanai',
        'dashboard.res_quiz': 'Gwaji',
        'dashboard.res_quiz_desc': 'Tambayoyin Gwaji',
        'dashboard.res_flashcards': 'Flashcards',
        'dashboard.res_flashcards_desc': 'Taimakon Tunawa',
        'dashboard.finalize': 'KAMMALA',
        'dashboard.mastery_confirmed': 'Gwaji Ya Kammala',
        'dashboard.mastery_desc': 'Kun gama gwajin.',
        'dashboard.resultant_yield': 'Dubawa',
        'hiw.hero_tag': 'Yadda Yake Aiki',
        'hiw.hero_title': 'Tsarin',
        'hiw.hero_title_span': 'Karatu',
        'hiw.hero_desc':
            'Canja daga bayanai zuwa ƙwarewa cikin matakai huɗu masu sauƙi.',
        'hiw.ingest_title': 'Loda',
        'hiw.ingest_desc': 'Loda PDFs ɗinku, bayanai, ko hotuna cikin tsaro.',
        'hiw.ingest_d1': 'Jawo da sakewa',
        'hiw.ingest_d2': 'Gane rubutu mai zurfi',
        'hiw.ingest_d3': 'Fahimtar gaggiwa',
        'hiw.ingest_d4': 'Babu iyakar girma',
        'hiw.neural_title': 'Binciken Smart',
        'hiw.neural_desc':
            "AI ɗinmu yana bincika abubuwan ku don fahimtar mahimman ra'ayoyi.",
        'hiw.neural_d1': 'Gano tsari',
        'hiw.neural_d2': 'Haɗin mahallin',
        'hiw.neural_d3': 'Fitar da mahimman kalmomi',
        'hiw.neural_d4': 'Goyon bayan harsuna daban-daban',
        'hiw.synth_title': 'Samar da Kayan Aiki',
        'hiw.synth_desc':
            'Izabi yana canza bayananku zuwa kayan karatu nan take.',
        'hiw.synth_d1': 'Takaitawa Masu Hikima',
        'hiw.synth_d2': 'Gwajin Gwaji',
        'hiw.synth_d3': 'Darussan Audio',
        'hiw.synth_d4': 'Taswirar Ilimi',
        'hiw.mastery_title': 'Gwada Ilimi',
        'hiw.mastery_desc':
            'Yi amfani da kayan aikin da aka samar don tabbatar da ilimin ku.',
        'hiw.mastery_d1': 'Kalubalanci Abokai',
        'hiw.mastery_d2': 'Bibiyar Ci gaba',
        'hiw.mastery_d3': 'Matsayin Duniya',
        'hiw.mastery_d4': 'Samun dama a waya',
        'hiw.lat_setup': 'Shiryawa',
        'hiw.lat_upload': 'Loda',
        'hiw.lat_neural': 'Tsari',
        'hiw.lat_mastery': 'Kwarewa',
        'hiw.cta_title': 'Kun shirya fara \nkaratu da Izabi?',
        'hiw.cta_btn': 'Kirkiri Asusun',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
    undefined,
);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>(
        () => (localStorage.getItem('izabi-lang') as Language) || 'en',
    );

    const setLanguage = (lang: Language) => {
        localStorage.setItem('izabi-lang', lang);
        setLanguageState(lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
