import type { StudyQuestionResponse } from '@/types/pdf';

export const LOCAL_PRACTICE_QUESTION_BANK: StudyQuestionResponse[] = [
    {
        question:
            'If you buy 3 notebooks for N450 each, how much do you spend in total?',
        options: ['N900', 'N1,350', 'N1,500', 'N1,800'],
        answer: 'N1,350',
        difficulty: 'easy',
        questionType: 'multiple_choice',
        explanation: '3 x 450 = 1,350.',
    },
    {
        question: 'Solve: 2x + 5 = 17',
        options: ['x = 4', 'x = 5', 'x = 6', 'x = 7'],
        answer: 'x = 6',
        difficulty: 'easy',
        questionType: 'multiple_choice',
        explanation: '2x = 12, so x = 6.',
    },
    {
        question: 'What is 25 percent of 200?',
        options: ['25', '40', '50', '75'],
        answer: '50',
        difficulty: 'easy',
        questionType: 'multiple_choice',
        explanation: '25% of 200 = 0.25 x 200 = 50.',
    },
    {
        question:
            'A rectangle has a length of 8 cm and a width of 5 cm. Find its area.',
        options: ['13 cm2', '26 cm2', '40 cm2', '80 cm2'],
        answer: '40 cm2',
        difficulty: 'easy',
        questionType: 'multiple_choice',
        explanation: 'Area = length x width = 8 x 5 = 40 cm2.',
    },
    {
        question: 'Simplify: 18 ÷ 3 × 2',
        options: ['3', '6', '12', '18'],
        answer: '12',
        difficulty: 'easy',
        questionType: 'multiple_choice',
        explanation: 'Division and multiplication are solved left to right.',
    },
    {
        question: 'What is 15 + 27?',
        options: ['32', '40', '42', '44'],
        answer: '42',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'A square has side length 6 cm. What is its perimeter?',
        options: ['12 cm', '24 cm', '30 cm', '36 cm'],
        answer: '24 cm',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What is 3/4 as a percentage?',
        options: ['25%', '50%', '75%', '80%'],
        answer: '75%',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What is 7 x 8?',
        options: ['54', '56', '58', '64'],
        answer: '56',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question:
            'Simple interest on N1,000 at 10% per year for 1 year is how much?',
        options: ['N10', 'N50', 'N100', 'N200'],
        answer: 'N100',
        difficulty: 'medium',
        questionType: 'multiple_choice',
        explanation: 'SI = P x R x T = 1000 x 0.1 x 1 = 100.',
    },
    {
        question:
            'Choose the correct word: She has fewer / less books than her brother.',
        options: ['fewer', 'less', 'fewest', 'least'],
        answer: 'fewer',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Choose the sentence that uses "because" correctly.',
        options: [
            'Because it was raining, we stayed indoors.',
            'We stayed indoors because.',
            'Because we stayed indoors it.',
            'Because raining, we stayed.',
        ],
        answer: 'Because it was raining, we stayed indoors.',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Identify the noun: "The teacher explained the lesson clearly."',
        options: ['explained', 'clearly', 'teacher', 'the'],
        answer: 'teacher',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Correct this sentence: "He don’t like reading novels."',
        options: [
            "He don't likes reading novels.",
            "He doesn't like reading novels.",
            'He did not likes reading novels.',
            'He not like reading novels.',
        ],
        answer: "He doesn't like reading novels.",
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What is the opposite of generous?',
        options: ['kind', 'stingy', 'helpful', 'friendly'],
        answer: 'stingy',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which word is closest in meaning to "rapid"?',
        options: ['slow', 'fast', 'quiet', 'late'],
        answer: 'fast',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Choose the correct plural form of "child".',
        options: ['childs', 'childes', 'children', 'childrens'],
        answer: 'children',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Identify the verb: "Birds fly high."',
        options: ['Birds', 'fly', 'high', 'the'],
        answer: 'fly',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Choose the correct sentence.',
        options: [
            'They is going to school.',
            'They are going to school.',
            'They am going to school.',
            'They be going to school.',
        ],
        answer: 'They are going to school.',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What is the capital city of Nigeria?',
        options: ['Lagos', 'Abuja', 'Kano', 'Port Harcourt'],
        answer: 'Abuja',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'How many days are in a leap year?',
        options: ['365', '366', '364', '360'],
        answer: '366',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Name one renewable source of energy.',
        options: ['Coal', 'Diesel', 'Solar', 'Petrol'],
        answer: 'Solar',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which planet is closest to the sun?',
        options: ['Venus', 'Earth', 'Mercury', 'Mars'],
        answer: 'Mercury',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What device is used to measure temperature?',
        options: ['Barometer', 'Thermometer', 'Hygrometer', 'Speedometer'],
        answer: 'Thermometer',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which is the largest ocean on Earth?',
        options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic'],
        answer: 'Pacific Ocean',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which gas do humans breathe in for survival?',
        options: ['Carbon dioxide', 'Hydrogen', 'Oxygen', 'Nitrogen'],
        answer: 'Oxygen',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What is the first month of the year?',
        options: ['December', 'January', 'March', 'June'],
        answer: 'January',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which planet is known as the Red Planet?',
        options: ['Mars', 'Jupiter', 'Neptune', 'Saturn'],
        answer: 'Mars',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'How many colors are in a rainbow?',
        options: ['5', '6', '7', '8'],
        answer: '7',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'If today is Wednesday, what day will it be in 10 days?',
        options: ['Friday', 'Saturday', 'Sunday', 'Monday'],
        answer: 'Saturday',
        difficulty: 'medium',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which number comes next: 2, 4, 8, 16, ___',
        options: ['18', '24', '30', '32'],
        answer: '32',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question:
            'If all cats are animals and some animals are pets, can some cats be pets?',
        options: ['Yes, it is possible.', 'No, impossible.', 'Only wild cats.', 'Only kittens.'],
        answer: 'Yes, it is possible.',
        difficulty: 'medium',
        questionType: 'multiple_choice',
    },
    {
        question:
            'A book costs N2,000. You pay with N5,000. How much change should you get?',
        options: ['N2,000', 'N2,500', 'N3,000', 'N3,500'],
        answer: 'N3,000',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'If you double a number and get 18, what is the number?',
        options: ['7', '8', '9', '10'],
        answer: '9',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'If A > B and B > C, which statement is true?',
        options: ['C > A', 'A > C', 'A = C', 'B = C'],
        answer: 'A > C',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question:
            'A train leaves at 3:00 PM and arrives at 5:30 PM. How long is the trip?',
        options: ['2 hours', '2 hours 30 minutes', '3 hours', '1 hour 30 minutes'],
        answer: '2 hours 30 minutes',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which number is the odd one out: 4, 9, 16, 20, 25?',
        options: ['4', '9', '20', '25'],
        answer: '20',
        difficulty: 'medium',
        questionType: 'multiple_choice',
    },
    {
        question: 'What does a web browser do?',
        options: [
            'Edits videos',
            'Helps you browse and view websites',
            'Repairs computers',
            'Prints documents',
        ],
        answer: 'Helps you browse and view websites',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Name one example of an email provider.',
        options: ['YouTube', 'Gmail', 'WhatsApp', 'Netflix'],
        answer: 'Gmail',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What does a password protect?',
        options: ['Your account and personal data', 'Your keyboard battery', 'Your internet speed', 'Your monitor color'],
        answer: 'Your account and personal data',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What is the main purpose of a search engine?',
        options: ['To draw pictures', 'To find information online', 'To format hard drives', 'To create passwords'],
        answer: 'To find information online',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question:
            'Which device is mainly used to type text into a computer?',
        options: ['Mouse', 'Monitor', 'Keyboard', 'Speaker'],
        answer: 'Keyboard',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which keyboard shortcut is commonly used to copy text?',
        options: ['Ctrl + X', 'Ctrl + V', 'Ctrl + C', 'Ctrl + Z'],
        answer: 'Ctrl + C',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which key is commonly used to refresh a web page?',
        options: ['F1', 'F5', 'F8', 'F12'],
        answer: 'F5',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
    {
        question: 'What does URL stand for?',
        options: ['Uniform Resource Locator', 'Universal Read Link', 'Unified Routing Label', 'User Reference Language'],
        answer: 'Uniform Resource Locator',
        difficulty: 'medium',
        questionType: 'multiple_choice',
    },
    {
        question: 'Which of these is a cloud storage service?',
        options: ['Google Drive', 'Calculator', 'Notepad', 'Bluetooth'],
        answer: 'Google Drive',
        difficulty: 'easy',
        questionType: 'multiple_choice',
    },
];
